# The URL the site will be built for
base_url = "https://open-mSupply-docs.msupply.org.nz"
default_language = "en"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "Adidoks"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# Set HTML file language
language_code = "en-US"

# More about site's title
title_separator = "-"  # set as |, -, _, etc
#itle_addition = "Open mSupply... Health Supply Chain Management for the World"

# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "America/New_York"

# Menu items
[[extra.menu.main]]
name = "Docs"
section = "docs"
url = "/docs/introduction/"
weight = 10
